### ISSUE TITLE
some initial problems getting this to run

### ISSUE THREAD

**Issue by leipzig** [pachterlab/PCACCA#1]
Hi this approach looks interesting. I am eager to see this manuscript reproduce!

A tiny issue so far:

* extra space at line 279

```
(PCA_CCA) Leipzig:PCACCA leipzig$ snakemake results
IndentationError in line 279 of /Users/leipzig/Documents/dev/PCACCA/Snakefile:
unexpected indent
```

**Comment by brielin** [comment]
Thanks for the report! I'm away from my computer for a few days but I'll be back online Friday and will take a look then.

**Comment by brielin** [comment]
I pushed a change on Friday that should fix this issue. I also removed the original config files, since as you pointed out initially they don't actually work unless you run the make_config yourself. Closing this issue. Thanks again for the report, let me know if you run into anymore trouble.
